branches:
  only:
  - master

environment:
  global:
    BUILD_FOLDER: C:\projects
  matrix:
  - BUILD_SYSTEM: bazel

install:
- appveyor DownloadFile https://github.com/bazelbuild/bazel/releases/download/0.10.0/bazel-0.10.0-windows-x86_64.exe -FileName bazel.exe

build_script:
  - 'cd plugin'
  - '..\bazel.exe build :protoc-gen-zsharp'
  - cd ..
  - .\build_proto.cmd
  - 'cd \runtime'
  - '.\build.cmd build'
  